# Generated by Django 2.2.1 on 2019-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Enfant', models.CharField(default='', max_length=20)),
                ('Prenom_Enfant', models.CharField(default='', max_length=20)),
                ('Date_De_Naissance', models.DateField(default='', verbose_name='Date de Naissance')),
                ('ArriveLundi', models.CharField(choices=[('', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('PartLundi', models.CharField(choices=[('', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('ArriveMardi', models.CharField(choices=[('', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('PartMardi', models.CharField(choices=[('', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('ArriveMercredi', models.CharField(choices=[('', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('PartMercredi', models.CharField(choices=[('', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('ArriveJeudi', models.CharField(choices=[('', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('PartJeudi', models.CharField(choices=[('', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('ArriveVendredi', models.CharField(choices=[('', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('PartVendredi', models.CharField(choices=[('', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
            ],
        ),
    ]
