# Generated by Django 2.2.1 on 2019-05-20 18:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_Parent', models.BooleanField(default=False)),
                ('is_Employe', models.BooleanField(default=False)),
                ('is_Contrib', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Enfant', models.CharField(max_length=20, verbose_name='nom')),
                ('prenom_Enfant', models.CharField(max_length=20, verbose_name='prenom')),
                ('dateDeNaissance_Enfant', models.DateField(verbose_name='Date de Naissance')),
                ('arriveLundi', models.CharField(choices=[('no', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('partLundi', models.CharField(choices=[('no', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('arriveMardi', models.CharField(choices=[('no', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('partMardi', models.CharField(choices=[('no', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('arriveMercredi', models.CharField(choices=[('no', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('partMercredi', models.CharField(choices=[('no', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('arriveJeudi', models.CharField(choices=[('no', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('partJeudi', models.CharField(choices=[('no', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
                ('arriveVendredi', models.CharField(choices=[('no', 'Ne Viens pas'), ('730', '7h30'), ('800', '8h00'), ('830', '8h30'), ('900', '9h00'), ('930', '9h30')], default='', max_length=3)),
                ('partVendredi', models.CharField(choices=[('no', 'Ne viens pas'), ('1630', '16h30'), ('1700', '17h00'), ('1730', '17h30'), ('1800', '18h00'), ('1830', '18h30')], default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intituleDuPoste', models.CharField(default='', max_length=100, verbose_name="Saisissez l'intitulé du poste")),
                ('DescriptionDuPoste', models.CharField(default='', max_length=999, verbose_name='Décrivez le poste')),
                ('diplomesRequis', models.CharField(default='', max_length=100, verbose_name='Saisissez quels dîplômes sont requis pour ce poste')),
                ('Contact', models.EmailField(default='asso.gros.calin@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Mere', models.CharField(max_length=20, verbose_name='Nom de la Mère')),
                ('prenom_Mere', models.CharField(max_length=20, verbose_name='Prénom de la Mère')),
                ('adresseMail_Mere', models.EmailField(max_length=254, verbose_name='Email de la Mère')),
                ('num_Mere', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='télephone de la Mère')),
                ('profession_Mere', models.CharField(max_length=64, verbose_name='Profession de la Mère')),
                ('telEmployeur_Mere', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="telephone de l'employeur de la Mère")),
                ('nom_Pere', models.CharField(max_length=20, verbose_name='Nom du Père')),
                ('prenom_Pere', models.CharField(max_length=20, verbose_name='Prénom du Père')),
                ('adresseMail_Pere', models.EmailField(max_length=254, verbose_name='Email du Père')),
                ('num_Pere', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='télephone du Père')),
                ('telEmployeur_Pere', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="telephone de l'employeur du Père")),
                ('profession_Pere', models.CharField(max_length=64, verbose_name='Profession du Père')),
                ('adresse', models.CharField(max_length=256, verbose_name='Adresse')),
                ('secondeAdresse', models.CharField(blank=True, max_length=256, verbose_name='Seconde Adresse')),
                ('nbEnfantAuFoyer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name="Nombre d'enfant au foyer")),
                ('parentUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
        migrations.CreateModel(
            name='ListeDAttente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCreche.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='EnfantPresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCreche.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('num', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='telephone')),
                ('horaireSemaineJaune', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune')),
                ('horaireSemaineRouge', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge')),
                ('horaireSemaineBleue', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue')),
                ('horaireSemaineVerte', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte')),
                ('horaireSemaineNoire', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire')),
                ('horaireSemaineRose', models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose')),
                ('adresseMail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utilisateur+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contributeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='prenom')),
                ('num', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='telephone')),
                ('adresseMail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utilisateur+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
