# Generated by Django 2.2.1 on 2019-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCreche', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant',
            old_name='nomAssurrance',
            new_name='nomAssurance',
        ),
    ]
