# Generated by Django 2.2.1 on 2019-05-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCreche', '0002_auto_20190520_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='prenom_Enfant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCreche.Enfant'),
        ),
    ]
