# Generated by Django 2.2.1 on 2019-05-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCreche', '0002_auto_20190527_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='empUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Utilisateur+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresseMail',
            field=models.EmailField(max_length=254, null=True, verbose_name="Email de l'employe"),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='arriveJeudi',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('7h30', '7h30'), ('8h00', '8h00'), ('8h30', '8h30'), ('9h00', '9h00'), ('9h30', '9h30')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='arriveLundi',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('7h30', '7h30'), ('8h00', '8h00'), ('8h30', '8h30'), ('9h00', '9h00'), ('9h30', '9h30')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='arriveMardi',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('7h30', '7h30'), ('8h00', '8h00'), ('8h30', '8h30'), ('9h00', '9h00'), ('9h30', '9h30')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='arriveMercredi',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('7h30', '7h30'), ('8h00', '8h00'), ('8h30', '8h30'), ('9h00', '9h00'), ('9h30', '9h30')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='arriveVendredi',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('7h30', '7h30'), ('8h00', '8h00'), ('8h30', '8h30'), ('9h00', '9h00'), ('9h30', '9h30')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='partJeudi',
            field=models.CharField(choices=[('no', 'Ne viens pas'), ('16h30', '16h30'), ('17h00', '17h00'), ('17h30', '17h30'), ('18h00', '18h00'), ('18h30', '18h30')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='partLundi',
            field=models.CharField(choices=[('no', 'Ne viens pas'), ('16h30', '16h30'), ('17h00', '17h00'), ('17h30', '17h30'), ('18h00', '18h00'), ('18h30', '18h30')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='partMardi',
            field=models.CharField(choices=[('no', 'Ne viens pas'), ('16h30', '16h30'), ('17h00', '17h00'), ('17h30', '17h30'), ('18h00', '18h00'), ('18h30', '18h30')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='partMercredi',
            field=models.CharField(choices=[('no', 'Ne viens pas'), ('16h30', '16h30'), ('17h00', '17h00'), ('17h30', '17h30'), ('18h00', '18h00'), ('18h30', '18h30')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='partVendredi',
            field=models.CharField(choices=[('no', 'Ne viens pas'), ('16h30', '16h30'), ('17h00', '17h00'), ('17h30', '17h30'), ('18h00', '18h00'), ('18h30', '18h30')], default='', max_length=5, null=True),
        ),
    ]
