# Generated by Django 2.2.1 on 2019-05-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCreche', '0003_auto_20190527_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineBleue',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineJaune',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineNoire',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineRose',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineRouge',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='horaireSemaineVerte',
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineBleue',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineJaune',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineNoire',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineRose',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineRouge',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireJeudiSemaineVerte',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineBleue',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineJaune',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineNoire',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineRose',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineRouge',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireLundiSemaineVerte',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineBleue',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineJaune',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineNoire',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineRose',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineRouge',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMardiSemaineVerte',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineBleue',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineJaune',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineNoire',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineRose',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineRouge',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireMercrediSemaineVerte',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineBleue',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Bleue'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineJaune',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Jaune'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineNoire',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Noire'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineRose',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rose'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineRouge',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Rouge'),
        ),
        migrations.AddField(
            model_name='employe',
            name='horaireVendrediSemaineVerte',
            field=models.CharField(choices=[('no', 'Ne Viens pas'), ('714', '7h00 - 14h00'), ('7143', '7h30 - 14h30'), ('815', '8h00 - 15h00'), ('9123', '9h00 - 12h30 / 14h45 - 18h15'), ('1045', '10h45 - 17h45'), ('1118', '11h00 - 18h00'), ('1130', '11h30 - 18h30')], default='', max_length=4, verbose_name='Horaires semaine Verte'),
        ),
    ]
