# Generated by Django 2.2.1 on 2019-06-05 13:56

import appCreche.path
import appCreche.validateurs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCreche', '0004_auto_20190527_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineBleue',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Bleue'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineJaune',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Jaune'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineNoire',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Noire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineRose',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Rose'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineRouge',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Rouge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireJeudiSemaineVerte',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Jeudi en semaine Verte'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineBleue',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Bleue'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineJaune',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Jaune'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineNoire',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Noire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineRose',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Rose'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineRouge',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Rouge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireLundiSemaineVerte',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Lundi en semaine Verte'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineBleue',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Bleue'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineJaune',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Jaune'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineNoire',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Noire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineRose',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Rose'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineRouge',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Rouge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMardiSemaineVerte',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mardi en semaine Verte'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineBleue',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Bleue'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineJaune',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Jaune'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineNoire',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Noire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineRose',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Rose'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineRouge',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Rouge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireMercrediSemaineVerte',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Mercredi en semaine Verte'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineBleue',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Bleue'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineJaune',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Jaune'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineNoire',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Noire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineRose',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Rose'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineRouge',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Rouge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='horaireVendrediSemaineVerte',
            field=models.CharField(choices=[('Ne viens pas', 'Ne Viens pas'), ('7h00 14h00 ', '7h00 - 14h00'), ('7h30 14h30', '7h30 - 14h30'), ('8h00 15h00', '8h00 - 15h00'), ('9h00 12h30 - 14h45 18h15', '9h00 - 12h30 / 14h45 - 18h15'), ('10h45 17h45', '10h45 - 17h45'), ('11h00 18h00', '11h00 - 18h00'), ('11h30 18h30', '11h30 - 18h30')], default='', max_length=25, verbose_name='Horaires du Vendredi en semaine Verte'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='AssuranceCivile',
            field=models.FileField(upload_to=appCreche.path.UploadToPathAndRename('AssuranceCivile'), validators=[appCreche.validateurs.validate_file_size], verbose_name="Assurance Civile de l'enfant "),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='AutorisationMedicament',
            field=models.FileField(upload_to=appCreche.path.UploadToPathAndRename('Autorisation Medicament'), validators=[appCreche.validateurs.validate_file_size], verbose_name="Autorisation de distribution de médicament de l'enfant "),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='FichePoliceAssurance',
            field=models.FileField(upload_to=appCreche.path.UploadToPathAndRename('Police Assurance'), validators=[appCreche.validateurs.validate_file_size], verbose_name="Police d'assurance de l'enfant "),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='certificatMedical',
            field=models.FileField(upload_to=appCreche.path.UploadToPathAndRename('CertificatMedical'), validators=[appCreche.validateurs.validate_file_size], verbose_name="Certificat Médical de l'enfant "),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='protocoleDeTemperature',
            field=models.FileField(upload_to=appCreche.path.UploadToPathAndRename('Protocole temp'), validators=[appCreche.validateurs.validate_file_size], verbose_name="Protocolde de température de l'enfant "),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='DescriptionDuPoste',
            field=models.CharField(default='', max_length=999, verbose_name='Décrivez le poste'),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='intituleDuPoste',
            field=models.CharField(default='', max_length=100, verbose_name='Intitulé du poste'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='FactureCreche',
            field=models.FileField(blank=True, null=True, upload_to=appCreche.path.UploadToPathAndRename('Factures'), validators=[appCreche.validateurs.validate_file_size], verbose_name='Dernière Facture : '),
        ),
    ]
